c
c-----Note: mnx is the MM5 west to east coordinate
c           mny is the MM5 south to north coordinate
c           mnz is the MM5 vertical coortinate
c
c           mnxc is the CAMx west to east coordinate
c           mnyc is the CAMx south to north coordinate
c           mnzc is the CAMx vertical coortinate
c
      integer mnx,mny,mnz,mnxc,mnyc,mnzc,numvals,numprogs
c
      parameter(mnx=200,mny=200,mnz=50)
      parameter(mnxc=200,mnyc=200,mnzc=40)
c
      parameter (numvals=1000,numprogs=20)
